-- this file contains the sql to create the sequences that will be used before creating the tables

CREATE SEQUENCE uid INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;
CREATE SEQUENCE mid INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;
CREATE SEQUENCE rid INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;